test_format = 1.0

[default]
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.3be74724da5be7f00da62de399f61a21bef37657.name = "Upgrade from 16.9.0"
